openapi: 3.0.0
info:
  title: Product Service API
  description: API for getting product information
  version: 1.0.0
servers:
  - url: https://faj5mo6ze7.execute-api.us-east-1.amazonaws.com/dev
    description: Development server
paths:
  /products:
    get:
      summary: Get all products
      description: Returns the full list of available products
      operationId: getProductsList
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '404':
          description: No products found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductsNotFoundError'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
  /products/{id}:
    get:
      summary: Get product by ID
      description: Returns a single product by ID
      operationId: getProductById
      parameters:
        - name: id
          in: path
          description: Product ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          description: Bad request - missing ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
        '404':
          description: Product not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductNotFoundError'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
components:
  schemas:
    Product:
      type: object
      required:
        - id
        - title
        - price
      properties:
        id:
          type: string
          description: Unique identifier for the product
          example: "1"
        title:
          type: string
          description: Name of the product
          example: "Product 1"
        description:
          type: string
          description: Description of the product
          example: "Product 1 description"
        price:
          type: number
          format: float
          description: Price of the product
          example: 89.99
    ProductNotFoundError:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: Error message
          example: "Product with ID {id} not found"
    ProductsNotFoundError:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: Error message
          example: "No products found"
    BadRequestError:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: Error message
          example: "Product ID is required"
    ServerError:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: Error message
          example: "Internal server error"